openapi: 3.2.0
info:
  title: papi Graphql API
  description: RunWhen Platform API
  version: 2.0.0
tags:
- name: Graph QL
paths:
  /graphql:
    get:
      summary: Handle Http Get
      operationId: handle_http_get_graphql_get
      responses:
        '200':
          description: The GraphiQL integrated development environment.
          content:
            application/json:
              schema: {}
        '404':
          description: Not found if GraphiQL or query via GET are not enabled.
      security:
      - BearerAuth: []
      tags:
      - Graph QL
    post:
      summary: Handle Http Post
      operationId: handle_http_post_graphql_post
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
      security:
      - BearerAuth: []
      tags:
      - Graph QL
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT access token from /api/v3/token/ or Auth0 login
