openapi: 3.1.0
info:
  title: papi alert-query-proxy API
  description: RunWhen Platform API
  version: 2.0.0
tags:
- name: alert-query-proxy
paths:
  /api/v1/alert-query/{path}:
    delete:
      tags:
      - alert-query-proxy
      summary: Proxy To Alert Query
      description: Proxy request to the internal alert-query service.
      operationId: proxy_to_alert_query_api_v1_alert_query__path__delete
      parameters:
      - name: path
        in: path
        required: true
        schema:
          type: string
          title: Path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - BearerAuth: []
    patch:
      tags:
      - alert-query-proxy
      summary: Proxy To Alert Query
      description: Proxy request to the internal alert-query service.
      operationId: proxy_to_alert_query_api_v1_alert_query__path__delete
      parameters:
      - name: path
        in: path
        required: true
        schema:
          type: string
          title: Path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - BearerAuth: []
    post:
      tags:
      - alert-query-proxy
      summary: Proxy To Alert Query
      description: Proxy request to the internal alert-query service.
      operationId: proxy_to_alert_query_api_v1_alert_query__path__delete
      parameters:
      - name: path
        in: path
        required: true
        schema:
          type: string
          title: Path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - BearerAuth: []
    put:
      tags:
      - alert-query-proxy
      summary: Proxy To Alert Query
      description: Proxy request to the internal alert-query service.
      operationId: proxy_to_alert_query_api_v1_alert_query__path__delete
      parameters:
      - name: path
        in: path
        required: true
        schema:
          type: string
          title: Path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - BearerAuth: []
    get:
      tags:
      - alert-query-proxy
      summary: Proxy To Alert Query
      description: Proxy request to the internal alert-query service.
      operationId: proxy_to_alert_query_api_v1_alert_query__path__delete
      parameters:
      - name: path
        in: path
        required: true
        schema:
          type: string
          title: Path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - BearerAuth: []
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
        input:
          title: Input
        ctx:
          type: object
          title: Context
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT access token from /api/v3/token/ or Auth0 login
